name: Python func

on:
    push:
        paths:
            - ".github/workflows/python-func.yml"
            - pyfunc/**
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Check python version
              run: python --version

            - name: Display current directory
              run: pwd

            - name: List files
              run: ls -R

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: List files
              run: ls -R
            
            - name: Install Python
              uses: actions/setup-python@v4
              with:
                    python-version: '3.13'
            
            - name: Check python version
              run: python --version 

            - name: Install Python Dependencies
              uses: py-actions/py-dependency-install@v4
              with:
                path: "pyfunc/requirements.txt"
                update-pip: "true"
            
            - name: Run tests
              working-directory: pyfunc
              run: pytest -v
              